### ISSUE TITLE
Bot de Extração de DANF-e's do site de Notas Fiscais

### ISSUE THREAD

**Issue by jjgouveia** [Ativos-Tecnologia/bot-extrator-danfe#1]

**Comment by RobsonFe** [comment]
### Bot Finalizado 

Todas as instruções de uso estão no `README.md` assim como também a instalação. 

- **Importante!** para utilização correta do bot, é necessário que o mouse esteja parado devido à utilização do `pyautogui`.

**Comment by RobsonFe** [comment]
### Bot corrigido e Finalizando. ``08-07-24``

O bot foi corrigido e finalizado, está pronto para uso. 
**É necessário** que o bot seja automatizado em um computador único, porque o processo exige automação com ``pyautogui`` e a movimentação do mouse pode interferir no processo.

**Comment by RobsonFe** [comment]
### Correção. ``09-07-2024``.

- Realizei no hoje uma correção no bot adicionando uma funcionalidade de reset em caso de erro, porque chega em um determinado momento que a segurança do site derruba o bot, caso ocorra, toda automação será reiniciada. 

<hr>

- Para facilitar no processo de automação, também coloquei uma função que configura tempos randômicos para cada passo da automação, dificultando para a segurança do site identificar o robô.
