### ISSUE TITLE
Analisar e aplicar uma alternativa ao Pyautogui

### ISSUE THREAD

**Issue by jjgouveia** [Ativos-Tecnologia/bot-extrator-danfe#2]

**Comment by RobsonFe** [comment]
### Processo do dia ``04-07-2024``

- Procurei outras formas de utilizar a automação para o processo de baixar as notas fiscais, porem sem sucesso devido as extensões que pesquisei e maioria resolvia ``captcha`` de forma paga. 
- Surgiu alguns problemas na automação com ``pyautogui``, então tive que resolver, porque o ``captcha`` começou a mudar a forma como abria o modal, além de erros também na extensão que resolve automaticamente o ``captcha``.  A forma que encontrei para lidar com esses erros, por enquanto, foi criando novas exceções para lidar com cada fase do ``captcha`` e pelo que pude testar, até o momento não falhou. 
- Também fiz algumas alterações no log e para salvar as chaves com erro em um ``txt``, pois anteriormente estava falhando também e tive que reajustar. 
- Instalei em outro notebook, o sistema que estamos desenvolvendo a pedido de **urgência** da contabilidade para pelo menos pegar as notas de 2019 para início do sistema.

**Comment by RobsonFe** [comment]
### Alternativa Provisória. ``09-07-2024``

Não consegui encontrar outra alternativa fora do ``pyautogui`` até o momento, porém estou utilizando um notebook extra para realizar a automação.

**Comment by RobsonFe** [comment]
### Processo do dia ``15-07-2024``. 

Encontrei uma alternativa ao ``PyAutoGui``, usando a biblioteca ``ActionChains``, voce pode fazer uma instancia do ``move_by_offset``. 

- Exemplo em Código. 

```python 

ActionChains(nav).move_by_offset( xoffset=563, yoffset=384).click().perform()
random_sleep() 
ActionChains(nav).move_by_offset(xoffset=660, yoffset=391).click().perform()
```

Embora exista essa alternativa, a biblioteca não funcionou como deveria, irei fazer alguns ajustes.
