### ISSUE TITLE
Criar uma forma de armazenar a ultima posição que foi buscada com sucesso na planilha para evitar que o robô de extração sempre recomece o processo desde o início

### ISSUE THREAD

**Issue by jjgouveia** [Ativos-Tecnologia/bot-extrator-danfe#3]

**Comment by RobsonFe** [comment]
### Processo do dia ``05-07-24``

A defesa do ``CAPTCHA`` está interceptando o bot, aumentando a defesa do site contra bot e impedindo o processo de automação, inclusive impedindo processos manuais até quando tento utilizar o site, pois o sistema de defesa pegou o meu IP. 

**Seguem algumas imagens.**

- Primeira Defesa Robusta 
![anti-bot](https://github.com/Ativos-Tecnologia/bot-extrator-danfe/assets/115955245/e6dbb070-6e0b-4b6a-903e-a0c9889606bf)
 --
- Segunda Defesa Robusta 

![anti-bot2](https://github.com/Ativos-Tecnologia/bot-extrator-danfe/assets/115955245/8986ff67-4d9e-4f5d-be73-da8199c249e0)

---
Att: Robson Ferreira.
